// Auto-generated by scripts/build-schema.js — do not edit by hand.
// The Zod schema in cli/lib/schema.js is the source of truth.

export interface CasaReadyConfig {
  app: string;
  envs: Record<string, Env>;
}

export interface Env {
  targets: Target[];
}

export interface Target {
  name: string;
  url: string;
  auth: FormAuth | SupabaseJwtAuth | NoAuth;
  /** Explicit list of URLs to seed ZAP's spider with (in addition to target.url). */
  seedUrls?: string[];
  /** Path to a directory whose subdirectory names become seed URLs (Supabase shortcut). */
  seedDir?: string;
  /** Per-target scan flavor override; defaults to the global --scan flag. */
  scan?: 'casa' | 'baseline' | 'oauth-callback';
  /** Required when scan='oauth-callback'. Query params used as fuzz starting input. */
  callbackParams?: Record<string, string>;
}

export interface FormAuth {
  type: 'form';
  loginUrl: string;
  loginRequestBody: string;
  usernameField: string;
  passwordField: string;
  loggedInIndicator: string;
}

export interface SupabaseJwtAuth {
  type: 'supabase-jwt';
  loginUrl: string;
  apiKey: string;
  refreshSeconds?: number;
}

export interface NoAuth {
  type: 'none';
}
