// Auto-generated by scripts/build-schema.js — do not edit by hand.
// The Zod schema in cli/lib/schema.js is the source of truth.

export interface CasaReadyConfig {
  app: string;
  envs: Record<string, Env>;
}

export interface Env {
  targets: Target[];
}

export interface Target {
  name: string;
  url: string;
  auth: FormAuth | SupabaseJwtAuth;
}

export interface FormAuth {
  type: 'form';
  loginUrl: string;
  loginRequestBody: string;
  usernameField: string;
  passwordField: string;
  loggedInIndicator: string;
}

export interface SupabaseJwtAuth {
  type: 'supabase-jwt';
  loginUrl: string;
  apiKey: string;
  refreshSeconds?: number;
}
