#!/usr/bin/env node
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { zodToJsonSchema } from 'zod-to-json-schema';
import { ConfigSchema } from '../cli/lib/schema.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

async function main() {
  const jsonSchema = zodToJsonSchema(ConfigSchema, {
    name: 'CasaReadyConfig',
    $refStrategy: 'root',
  });
  jsonSchema.$schema = 'http://json-schema.org/draft-07/schema#';
  jsonSchema.title = 'CASA Ready Config';
  jsonSchema.description =
    'Schema for casa-ready.yml. See https://github.com/elagerway/casa-ready';

  const schemaDir = path.join(ROOT, 'schemas');
  await mkdir(schemaDir, { recursive: true });
  const schemaPath = path.join(schemaDir, 'casa-ready.schema.json');
  await writeFile(schemaPath, JSON.stringify(jsonSchema, null, 2) + '\n', 'utf8');
  console.log(`✓ wrote ${path.relative(ROOT, schemaPath)}`);

  // Hand-crafted .d.ts (rather than zod-to-ts) — discriminated unions don't
  // survive the auto-conversion cleanly. Hand-rolled keeps the published
  // surface predictable and small.
  const dts = `// Auto-generated by scripts/build-schema.js — do not edit by hand.
// The Zod schema in cli/lib/schema.js is the source of truth.

export interface CasaReadyConfig {
  app: string;
  envs: Record<string, Env>;
}

export interface Env {
  targets: Target[];
}

export interface Target {
  name: string;
  url: string;
  auth: FormAuth | SupabaseJwtAuth | NoAuth;
  /** Explicit list of URLs to seed ZAP's spider with (in addition to target.url). */
  seedUrls?: string[];
  /** Path to a directory whose subdirectory names become seed URLs (Supabase shortcut). */
  seedDir?: string;
  /** Per-target scan flavor override; defaults to the global --scan flag. */
  scan?: 'casa' | 'baseline' | 'oauth-callback';
  /** Required when scan='oauth-callback'. Query params used as fuzz starting input. */
  callbackParams?: Record<string, string>;
}

export interface FormAuth {
  type: 'form';
  loginUrl: string;
  loginRequestBody: string;
  usernameField: string;
  passwordField: string;
  loggedInIndicator: string;
}

export interface SupabaseJwtAuth {
  type: 'supabase-jwt';
  loginUrl: string;
  apiKey: string;
  refreshSeconds?: number;
}

export interface NoAuth {
  type: 'none';
}
`;

  const typesDir = path.join(ROOT, 'types');
  await mkdir(typesDir, { recursive: true });
  const typesPath = path.join(typesDir, 'index.d.ts');
  await writeFile(typesPath, dts, 'utf8');
  console.log(`✓ wrote ${path.relative(ROOT, typesPath)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
